### ISSUE TITLE
Problem with VMSS

### ISSUE THREAD

**Issue by miqm** [fluffy-cakes/azure_egress_nat#1]
Hi,

I stumbled on your repo while trying to build an Azure NVM that will act as forwarder for testing purposes. However I have problem with the waagent - it needs to connect to same IP as load balancer probes - however the wire server works only on the primary nic, not the secondary. and the route you add for the load balancer probe to work makes the outgoing http request to fail - as it cannot reach WireServer.

Do you know if there is some workaround? potentially chaning primary nic could resolve the issue but then we'd need to mess up with default route...

**Comment by fluffy-cakes** [comment]
Hi, sorry for the belated reply, I missed this message.

One thought that comes to mind is that you could potentially use one NIC to do both jobs of eth0 and eth1, however that would require creating VLANs inside the Ubuntu box and creating a number of custom routes. So eth0 will be the card, and VLAN 1 would be eth0.1 and VLAN 2 would be eth0.2. I use this set up in OpenWRT, which is obviously not the same as Ubuntu, but it still uses the same basic Linux tools to accomplish the same tasks (IP Tables). 

This is all off the top of my head guess, I hadn't come into the problem you're experiencing, and it's been a while since I set this up.

**Comment by miqm** [comment]
Overall I ended up with setting private NIC as primary and adding default route via eth1 at the beginning of the custom script extension.
